project:
  title: "computo-quarto-extension"
  render: 
    - computo-quarto-extension.qmd
  resources: 
    - environment.yml

title: "Challenging estimation of tuning parameters in sPLSDR model to predict the incidence of rare diseases"
date: 06/10/2025
date-modified: last-modified
author:
  - name: Ian Meneghel Danilevicz 
    corresponding: true
    email: ian.meneghel-danilevicz@inserm.fr 
    url: https://github.com/iandanilevicz/
    orcid: 0000-0003-4541-0524
    affiliations:
      - ref: univ1
  - name: Sam Vidil
    corresponding: false
    orcid: 0009-0007-6414-3966
    affiliations:
      - ref: univ1
  - name: Séverine Sabia
    corresponding: false
    orcid: 0000-0003-3109-9720
    affiliations:
      - ref: univ1
      - ref: univ2
affiliations:
  - id: univ1
    name: Université Paris Cité, Inserm, Center for Research in Epidemiology and Statistics (CRESS)
    department: EpiAgeing
    address: 
    city: Paris
    country: France
    postal-code: 75004
  - id: univ2
    name: University College London, 
    department: UCL Brain Sciences, Division of Psychiatry
    address: 
    city: London
    country: UK
    postal-code: W1T 7NF    
description: |
  This document provides a template based on the quarto system for contributions to Computo. 
  The github repository in itself provides a specific quarto extension useful for authors (and editors!).
keywords: [Machine learning, Survival analysis, Variable selection, Cross-validation, Bootstrap]
abstract: |
  We investigate some practical points of the sparse partial least squares deviance residuals (sPLSDR) model, 
  a machine learning (ML) method with important application potential and a powerful alternative for Cox regression 
  analysis when dimension reduction and variable selection are required. It can be used in a broad range of 
  contexts, among which the health domain. This method requires to tune two hyper-parameters: eta (sparsity level) 
  and D (number of components). Usually, the literature recommends cross-validation (CV) with a number of folds 
  that depends on the sample size to estimate the hyperparameters. However, in case of dichotomous outcome for 
  which the ratio of cases and non-cases is small this approach appears to be unstable. This is the case in rare 
  disease such as incidence of major neurocognitive disorder (NCD). In that case, even large samples may perform 
  as poorly as small samples. We specifically test this scenario of large samples with rare events using Monte 
  Carlo simulations with different performance criteria (C-index and AIC). We observed that five folds are 
  more conservative (biased) than one fold, and it presents more variability (less precise) in case of rare 
  event outcomes. Previous authors suggested that Bootstrap or leave-one-out (LOO) could be a wise alternative. 
  We checked Bootstrap with one fold in our real analysis application using the Whitehall II accelerometer 
  sub-study (N total = 3,969,  cases = 291 (7.3%)) as a training set and the UK Biobank as a validation set 
  (N total = 54,833,  cases = 750 (1.4\%)), both considerably large sample size studies, with incidence of 
  major neurocognitive disorders as an example of rare outcomes. This application shows that CV is sensitive 
  to the number of folds and the initial seed. The counterpart Bootstrap was more robust and displayed two 
  components with eta equal to 0.75 as a consistent optimum choice for the tuning parameters. However, this 
  approach requires external validation, which is not always feasible. Further studies can better map the 
  ideal number of folds for CV depending on the sample size and the ratio of cases/non-cases. As dichotomous 
  outcomes and survival time are classical statistical subjects, the ML literature provide clear and precise 
  recommendations for several available dawn methods.
bibliography: references.bib
google-scholar: true
github-user: computorg
repo: "computo-quarto-extension"
draft: true # set to false once the build is running
published: false # will be set to true once accepted
format:
  computo-html: default
  computo-pdf: default

diagram:
  engine:
    tikz:
      header-includes:
        - '\usetikzlibrary{arrows}'


