name: Main Workflows

on:
  push:
    branches: ["main","master"]
  repository_dispatch:
    types: [custom-event]
  workflow_dispatch:
  pull_request:
    branches: ["main","master"]

jobs:
  call_env_workflow:
    uses: computorg/workflows/.github/workflows/global-env.yml@main

  install_deps:
    runs-on: ubuntu-latest
    needs: call_env_workflow
    steps:
      - name: Install LAPACK and BLAS
        run: |
          sudo apt-get update
          sudo apt-get install -y liblapack-dev libblas-dev gfortran

  call_quartopublish_workflow:
    permissions:
      id-token: write
      contents: write
      pages: write
    uses: computorg/workflows/.github/workflows/publish-render.yml@main
    needs: [call_env_workflow, install_deps]

